### ISSUE TITLE
Error of Cities model downloaded from CCL

### ISSUE THREAD

**Issue by SCAUFINN** [NetLogo/NetLogo#1715]
From official:
_Hi Finn, so it is a problem due to netlogo versions. This was right around the time that we implemented a major change in the NetLogo model file format._

_You should download NetLogo 4.0 (found here: https://ccl.northwestern.edu/netlogo/4.0.0/) This is old enough that there may be compatibility issues with your OS but if there aren't then the model should run just fine._

If you meet the same problem, hope this solution could help you.
I am soooo grateful to whom replied me these days from the bottom of my heart. Thank you guys!

____________________________Separate Line__________________________

I download Cities CORE model [on this page](http://ccl.northwestern.edu/rp/cities/core.shtml), both on Windows an Mac OS system. However, en error pops up saying that “can’t open extension file: <path>/cities.jar” on Mac OS while showing that “Expected logo file to have 12 sections, this had 11” on Windows.

Could anyone help me to fix up the problem?

Thanks all of you! I’m so surprised to receive so many replies in a minute. I did download netlogo 4.0.5 on Mac OS system and Windows. However the problem still exists. Actually the interface does display but the model can’t run (on Mac OS).

Other functions and models work well except for this Cities.nlogo file. Did anyone try it successfully before? I would be very grateful if you could recommend some similar models for me! Thanks!!

**Comment by SethTisue** [comment]
you'll need to try it using NetLogo 4.0.5. the Cities model requires that specific NetLogo version, it was never updated for more recent versions

NetLogo 4 is from 2009. whether it will even still run on modern computers, I'm not sure

**Comment by LaCuneta** [comment]
Link to 4.0.5: http://ccl.northwestern.edu/netlogo/4.0.5/

**Comment by nicolaspayette** [comment]
Another version of that extension is hosted at: http://lovelace.augustana.edu/files/cities.zip.

I think it has worked better for some users in the past.

**Comment by SCAUFINN** [comment]
Thanks @nicolaspayette ! I try to open your link but it says that  “The requested URL /files/cities.zip was not found on this server. Apache/2.4.29 (Ubuntu) Server at lovelace.augustana.edu Port 80”.

**Comment by nicolaspayette** [comment]
Yeah, sorry, I just realised that myself. If I remember correctly, that version was originally dug up by @fstonedahl. Not sure if he still has a copy lying around... ?

**Comment by SCAUFINN** [comment]
@SethTisue Thanks for your specific replies! I try to run other models on Netlogo 4 just now but they  work well on Mac OS except for this model. Really weird.

**Comment by SCAUFINN** [comment]
@nicolaspayette So grateful!

**Comment by fstonedahl** [comment]
Ah yes, our lovelace web server had to be rebuilt last year, and that [cities.zip](http://lovelace.augustana.edu/files/cities.zip) file containing the extension didn't get transferred over.  I've put it back up.  Also, here's a link to the ancient [cities models](http://lovelace.augustana.edu/files/cities-model-files.zip) too.

Nonetheless, I stand by my earlier statement from a mailing list discussion about this:

> For anyone interested in doing serious follow-up on the CITIES project... my memory is that the cities model (while impressive) can be a real pain to work with... and I'm very doubtful about porting the model and its accompanying extension to a modern version of NetLogo.
> 
> It would be much better in the long run to simply take some inspiration from the CITIES project, but make a clean start for an urban development simulator using a more modern version of NetLogo, and take advantage of better language features like tasks.  (Just my two cents.)

**Comment by SCAUFINN** [comment]
@fstonedahl  Nice resource, thank you! I successfully download it but it still pops up “Expected logo file to have 12 sections, this had 11” when I try to open it. I suppose something wrong with my computer(Windows system).

**Comment by charlesres** [comment]
@SCAUFINN The Cities.nlogo model is saved with NetLogo 4.0 beta and won't work with NetLogo 6. After some tests, NetLogo 4.0.1 seems to be the best version since, for me, NetLogo 4.0 and NetLogo 4.0.5 do not load/run the model properly (Linux).

**Comment by SCAUFINN** [comment]
@charlesres  you’re totally right! I download Netlogo 4.0.0 just now and the problem disappear but a now come up saying “Can’t open file: /...(filepath)../cities.jar”. 😓Endless sadness..

**Comment by SethTisue** [comment]
do you have cities.jar in the same folder with the main .nlogo file?

**Comment by SCAUFINN** [comment]
@SethTisue Yeah, I check it again and again. Maybe I should download any other thing to support the file?

**Comment by charlesres** [comment]
Hi, @SCAUFINN. I wanted to confirm that this issue has been resolved with the Cities.nlogo model. I see that you edited the main comment above, mentioning this discussion as a solution.

**Comment by SCAUFINN** [comment]
@charlesres actually the problem isn’t totally solved. The model still can’t open the extension “cities.jar” so I’m waiting for the reply from netlogo official. If there’s any new development, I will update the comment asap.

**Comment by SethTisue** [comment]
I downloaded NetLogo 4.0.5 but it wouldn't run on my MacOS 10.14.3 system:

<img width="532" alt="Screen Shot 2019-03-08 at 8 45 10 PM" src="https://user-images.githubusercontent.com/161079/54064549-47d47b80-41e3-11e9-9f58-f6476f59a78c.png">

I also tried 4.0.0 and 4.0.1 but neither of them would launch — I didn't get any error message, but nothing happened, either. So I'm not able to troubleshoot this any further.

**Comment by SCAUFINN** [comment]
@SethTisue Thank you, I so appreciate it! This problem didn’t pop up when I run Netlogo 4.0.5 on my Mac system(10.14.4), however, the official did say that the old version may not run on modern Mac OS system. It seems that Netlogo has a various potential problems😰

**Comment by samudzi** [comment]
@fstonedahl Are there other projects you are aware of that do take inspiration from the cities model?  Or would someone likely have to finance such an effort?

If the latter, I'm willing to do so, but would need some help in actually scoping such a project.

**Comment by fstonedahl** [comment]
I'm afraid I'm not really an expert in this area --I was just helping out with the CITIES project toward the end of its life span.  

If you aren't talking about NetLogo specifically, then a literature search for "ABM urban growth" or perhaps "ABM land use and development", or something along those lines may bring up relevant research papers.  e.g. here were a couple of the first ones that popped up:

- https://www.sciencedirect.com/science/article/abs/pii/S0264275113000061 
- https://core.ac.uk/download/pdf/16247712.pdf

If you are specifically interested in urban growth/development models **using NetLogo**, then you could try searching the ComSES Net models library https://www.comses.net/codebases/ .  Many of the models in that library are written in NetLogo.  However, again, I don't know of other projects similar to the CITIES project of the top of my head.  

Finally, I think you might also want to take a close look at some of Michael Batty's work/books, regarding cities and complexity.
See: http://www.complexcity.info/

I suspect that if sufficient funding was available there would be people interested/willing for working on a project like this.  Someone who is currently at the CCL might be able to give you a better sense of cost & scope for something like that.

**Comment by SethTisue** [comment]
I suggest this ticket be closed, as there is no realistic possibility of anything really changing here.

**Comment by samudzi** [comment]
Agreed, @SethTisue 

For those who stumble on this thread in the future, I found this one that is somewhat unpolished, but serves as a great general template for building your own land use ABM with netlogo:
https://www.comses.net/codebases/acc61c38-4a67-4183-868f-d11fe70aa290/releases/1.0.0/
