### ISSUE TITLE
Bundle M1-native JVM on M1 Macs?

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#2016]
I think NetLogo users on M1 Macs might see major performance gains if you did this. I haven't tested NetLogo in particular, but since I got an M1 Mac and switched to M1-Native JDK 17, everything I do on the JVM is, like, 2x faster, something like that.

related: #1500

**Comment by SethTisue** [comment]
is this resolved by #2045?

**Comment by LaCuneta** [comment]
@SethTisue

> is this resolved by https://github.com/NetLogo/NetLogo/pull/2045?

Unfortunately, no.  We still lack an M1 or M2 computer to do the updates and testing on.

**Comment by EwoutH** [comment]
Would cross-compilation work, if we then list it as a experimental build? Users will then report potential bugs to us, and after a few releases we might deem it stable.

Slightly related, are exact build scripts available somewhere? Should we add them to the CI?

**Comment by SethTisue** [comment]
> Slightly related, are exact build scripts available somewhere? Should we add them to the CI?

It's all in CI. There is substantial automation, and some manual steps. The process of making release bundles is documented at https://github.com/NetLogo/NetLogo/wiki/Releasing

**Comment by EwoutH** [comment]
Do you think it would be possible to add the last manual steps to the CI? Then it is fully reproducible, can be tested easily and makes more frequent (bug fix) releases easier.

It also allows for experimentation with other platforms, notably Arm64 macOS and Windows.

**Comment by ERSUCC** [comment]
I have not had any issues with JOGL on my M1 Mac, and I am able to run the 3D samples in the models library. Seems like this issue has been resolved.

**Comment by LaCuneta** [comment]
@ERSUCC The potential problem I was pointing out would be with an ARM-native version of NetLogo, not the current universal architecture JVM.  I haven't been keeping up, but JOGL still doesn't seem to have an ARM-specific version available in their latest 2.5:  https://jogamp.org/deployment/archive/rc/v2.5.0/jar/

**Comment by ERSUCC** [comment]
This is now implemented, and will be offered starting with the upcoming beta release of NetLogo 7.
