### ISSUE TITLE
Behaviour space experiments do not run with patched model

### ISSUE THREAD

**Issue by bop20no** [NetLogo/NetLogo#2082]
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

SET expected 2 inputs. at position 304 in 
 at org.nlogo.core.Fail$.exception(Fail.scala:27)
 at org.nlogo.core.Fail$.exception(Fail.scala:25)
 at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:233)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
 at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
 at scala.collection.immutable.Range.foreach(Range.scala:158)
 at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
 at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
 at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:69)
 at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
 at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
 at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
 at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
 at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
 at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
 at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
 at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
 at scala.collection.Iterator.foreach(Iterator.scala:943)
 at scala.collection.Iterator.foreach$(Iterator.scala:943)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
 at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:213)
 at scala.collection.TraversableLike.map(TraversableLike.scala:285)
 at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
 at scala.collection.AbstractTraversable.map(Traversable.scala:108)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:47)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:85)
 at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:100)
 at org.nlogo.workspace.Evaluator.invokeCompiler(Evaluator.scala:159)
 at org.nlogo.workspace.Evaluator.evaluateCommands(Evaluator.scala:20)
 at org.nlogo.workspace.Evaluating.command(Evaluating.scala:80)
 at org.nlogo.workspace.Evaluating.command$(Evaluating.scala:79)
 at org.nlogo.workspace.AbstractWorkspaceScala.command(AbstractWorkspaceScala.scala:26)
 at org.nlogo.headless.HeadlessModelOpener.finish(HeadlessModelOpener.scala:112)
 at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:74)
 at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:539)
 at org.nlogo.app.App$$anon$1.openCurrentModelIn(App.scala:134)
 at org.nlogo.lab.gui.Supervisor.$anonfun$start$1(Supervisor.scala:98)
 at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
 at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:96)
 at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:103)
 at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:30)
 at org.nlogo.lab.gui.ManagerDialog$$anon$1.actionPerformed(ManagerDialog.scala:24)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
 at java.awt.Component.processMouseEvent(Component.java:6539)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
 at java.awt.Container.dispatchEventImpl(Container.java:2283)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.2.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.12
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: AselModel_1Patch

02:34:41.475 RemoveJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
02:34:41.474 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
02:34:41.472 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:34:41.472 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:34:41.472 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:34:41.472 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:34:41.472 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:34:41.472 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:34:41.472 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
02:34:41.472 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread

**Comment by brandesNW** [comment]
Thank you for reporting this error and sharing the message produced. 
We will need more information to help you.

I see you are running NetLogo 6.2.0. We have released several version since then and code that runs on 6.2.0 should run without changes on NetLogo 6.3.0, our latest release available at https://ccl.northwestern.edu/netlogo/download.shtml.  I suggest you download and install it and run your program again. This probably won't fix your problem, but we test and make updates based on the current release. 

I notice you call this a patched model  *AselModel_1Patch*. Is there a previous model that did not give this error? Looking at the changes might help locate the source of the problem.

We would appreciate it if you take as many of the steps below as you can to either solve  or narrow down the problem.

I assume  your model run successfully without BehaviorSpace under some conditions. However one possibility is that BehaviorSpace is testing a combination of inputs that are an 'edge case' in which your algorithm breaks down.
For that reason I suggest you make use of [Table output](https://ccl.northwestern.edu/netlogo/docs/behaviorspace.html#run-options-formats).
Since data is added to the file for each run you should be able to find the values of the initial variable values for the run that fails. Run your model with those values (without BehaviorSpace) and see if you get the same error.  If you do the problem is not with BehaviorSpace. It is either a NetLogo issue, or a problem with your code.
Based on the error message and stack trace the code that is causing the problem involves the use of the primitive `set` in an anonymous function that uses a function that can take a variable number of arguments.
The relevant lines are:

> org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
> org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)

As indicated in the [documentation](https://ccl.northwestern.edu/netlogo/docs/dictionary.html#set)
The syntax for `set` is 
set *variable value*
so the code is either failing to get a value, or is getting more than one value.

If you are able to locate the relevant code you can print (or use another [output command](http://ccl.northwestern.edu/netlogo/docs/programming.html#output)) the input to the let command before the use of the command. That will hopefully enable you to see the incorrect input, which may enable you to fix the problem.

If the problem seems to be with NetLogo, or you cannot resolve it using the ideas about can you send us the model, as well as either the initial conditions that produce the error, or the BehaviorSpace experiment you run, along with any non-default values you set.

GitHub does not accept .nlogo files as input. To work around this you can either put your model in a zip file, or change the extension to .txt and then attach it.
If you have a previous working version of the model feel free to include it.
We are sorry you have encountered this problem.
- Aaron

**Comment by bop20no** [comment]
Dear Aaron,

Thank you for your rapid response.

I've downloaded the latest version of NetLogo and still have the same
issue.
A previous version of the model that worked in behaviourSpace did not have
patches explicitly - behaviourSpace stopped working once I implemented
patches.
I ran the patch model with a table output - the table output is empty.
I can't see any lines that could potentially fail to get a value, or is to
more than one value.

Even when I run behaviour space with the default values and most basic
output, I still don't run and the table file is empty - so could it be
something with the setup?

Does the above message indicate what line of code the error is in?

Best wishes,
Niamh

**Comment by brandesNW** [comment]
Hi Niamh,
I’m sorry your problem has persisted.
Thanks for upgrading to NetLogo 6.3.
The line numbers in the error message refer to the code that makes NetLogo work and does not explicitly refer to line numbers in your NetLogo Code tab.
Does your model run correctly without BehaviorSpace? If it does, but fails with BehaviorSpace that would likely be an issue with NetLogo itself. In that case we definitely need your model in order to reproduce the problem by because by default a new experiment uses the values set in the widgets (sliders, switches, choosers, inputs). To check that that they are valid click on your experiment and look at the values set in the text block below the line Vary variables as follows. If you haven’t edited them entries should have the form [“my-variable-name” value].

The only additional thought I have about problems that might be in your code would be if it refers to patches by coordinates that are variables such as patch xvar yvar that are outside the limits of your world. You can see those limits by clicking the Settings … tab that is located towards the top right of the Interface and could print out the coordinates to make sure they are valid.

Please follow up with more information.

By the way the Netlogo Users Group<https://groups.google.com/g/netlogo-users> is a good resource for help with NetLogo programming.

Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: bop20no ***@***.***>
Date: Friday, February 17, 2023 at 6:27 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Comment ***@***.***>
Subject: Re: [NetLogo/NetLogo] Behaviour space experiments do not run with patched model (Issue #2082)
Dear Aaron,

Thank you for your rapid response.

I've downloaded the latest version of NetLogo and still have the same
issue.
A previous version of the model that worked in behaviourSpace did not have
patches explicitly - behaviourSpace stopped working once I implemented
patches.
I ran the patch model with a table output - the table output is empty.
I can't see any lines that could potentially fail to get a value, or is to
more than one value.

Even when I run behaviour space with the default values and most basic
output, I still don't run and the table file is empty - so could it be
something with the setup?

Does the above message indicate what line of code the error is in?

Best wishes,
Niamh

**Comment by bop20no** [comment]
Thank you Aaron, I appreciate you taking the time

Yes, the model runs without behaviour space.

Please find attached a version of the model. For now, for simplicity, the
turtles exist in a 1 patch world.
In this file there are two experiments. The first "
Baseline_DefaultValues"  uses default values that run without behaviour
space, and simple reporters (i.e. time). The second, "Baseline_Test", has
non default values for variables and other reporters.

I really appreciate you taking a look at this. I would also appreciate it
if you did not share the model as it is still a part of an ongoing project.

Thank you and Best wishes,
Niamh

**Comment by bop20no** [comment]
Thank you Aaron, I appreciate you taking the time

Yes, the model runs without behaviour space.

Is it possible to send the model privately? The model is part of an ongoing project

I really appreciate you taking a look at this. 

Thank you and Best wishes,
Niamh

**Comment by brandesNW** [comment]
Hi Niamh,
You can send it to me directly at ***@***.******@***.***>.

It is possible that you have encountered an unusal situation due to the use of only one patch.
You don’t have to zip the model if sending it directly.
- Aaron
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: bop20no ***@***.***>
Date: Friday, February 17, 2023 at 11:44 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Aaron Andre Brandes ***@***.***>, Comment ***@***.***>
Subject: Re: [NetLogo/NetLogo] Behaviour space experiments do not run with patched model (Issue #2082)

Thank you Aaron, I appreciate you taking the time

Yes, the model runs without behaviour space.

Is it possible to send the model privately? The model is part of an ongoing project

I really appreciate you taking a look at this.

Thank you and Best wishes,
Niamh

**Comment by brandesNW** [comment]
The model is part of on-going research and the user has shared it privately.
I was able to reproduce the error using 2 threads, and found that it does not occur using 1 thread.

**Comment by brandesNW** [comment]
The complexity of the model obscured the cause of the error. The user has a slider with the variable *random-number* which is the name of a NetLogo primitive that is called in the code. When BehaviorSpace is run with multiple threads this causes a problem. 
The user can fix their problem by renaming the slider variable to *random_seed* and removing the global variable called *random_seed*.

The user may find the section
[Random Numbers](http://ccl.northwestern.edu/netlogo/docs/programming.html#random-numbers) of the Programming Guide to be helpful in terms of creating behavior space experiments with distinct random seeds.
