### ISSUE TITLE
Note Transparency

### ISSUE THREAD

**Issue by kgmt0** [NetLogo/NetLogo#2369]
With the new GUI, notes no longer have an option to use transparent background. If you open a model built with the old GUI, notes will gain a solid white background, which is not always desirable. For example, I've run into a model that has notes overlaid on top of the view. The notes have transparent background and white text. With the new GUI, the notes gain solid white background, so the texts become unreadable.

![Image](https://github.com/user-attachments/assets/e4b6dd37-1d2f-48f1-b162-b5e21ac660f6)
![Image](https://github.com/user-attachments/assets/b4738c1c-3492-4fe0-9344-c3a2873b4be9)

**Comment by ERSUCC** [comment]
Good catch. Fixed in commit [bccbad7](https://github.com/NetLogo/NetLogo/commit/bccbad771d7cb084130648f299f601ddd4cd239b). I'm not sure which model you're referring to, so I can't check whether the transparency of its existing widgets have been preserved, but you can now create new note widgets with transparency. If it seems that the transparency has been lost on any existing models, let me know and I'll fix that as well.

**Comment by kgmt0** [comment]
> Good catch. Fixed in commit bccbad7. I'm not sure which model you're referring to, so I can't check whether the transparency of its existing widgets have been preserved

Thanks for the fix, but the transparency is still not being preserved. You can test with this model: [test.nlogo.txt](https://github.com/user-attachments/files/19483594/test.nlogo.txt). I had to add `.txt` to the filename so that GitHub will allow me to upload the file, but you can just remove it.

**Comment by ERSUCC** [comment]
Sorry, I was testing with .nlogox files, not with .nlogo files. It should now be fixed.

**Comment by kgmt0** [comment]
Thanks, I can confirm that transparency is being preserved now.
