### ISSUE TITLE
Low Contrast in Code Blocks When Using Dark Theme (NetLogo 7.0.0-beta2)

### ISSUE THREAD

**Issue by danielvartan** [NetLogo/NetLogo#2540]
Hi there,

Minor bug: When using the dark theme, code blocks on the Info tab are rendered with text that lacks sufficient contrast—making them hard to read (see image below). The text color should be white or otherwise adjusted to ensure proper readability against the dark background.

<img width="646" height="340" alt="Image" src="https://github.com/user-attachments/assets/73776650-27bc-438a-88e5-2723dee7b9c8" />

## Environment

NetLogo 7.0.0-beta2 (July 18, 2025)
Extension API version: 7.0
OpenJDK 64-Bit Server VM 17.0.2 (Oracle Corporation; 17.0.2+8-86)
Operating System: Linux 6.16.5-arch1-1 (amd64 processor)
Scala 3.7.0
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

Thank you!

**Comment by ERSUCC** [comment]
Fixed in commit [14111a4](https://github.com/NetLogo/NetLogo/commit/14111a475319cd2c6ef5b258049e1c238706d32b).

**Comment by danielvartan** [comment]
Hi there,

This issue persists in NetLogo 7.0.3.

<img width="736" height="690" alt="Image" src="https://github.com/user-attachments/assets/8b7fd6d2-6c53-4db3-9481-61346d4d1ddd" />

## System

NetLogo 7.0.3 (December 1, 2025)
Extension API version: 7.0
OpenJDK 64-Bit Server VM 17.0.2 (Oracle Corporation; 17.0.2+8-86)
Operating system: Linux 6.18.2-arch2-1 (amd64 processor)
Scala 3.7.0
Java heap: used = 76 MB, free = 140 MB, max = 15896 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

**Comment by ERSUCC** [comment]
Hi @danielvartan,

Thanks for the report, it did indeed get un-fixed somehow. Luckily, it was since re-fixed, in commit [176897b](https://github.com/NetLogo/NetLogo/commit/176897b7761169b6941551a9b172aef3e145026f). Should be fixed for good in the next release!
